name: lein test
on:
  - push
  - pull_request

jobs:
  lein-test:
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Install dependencies"
          sudo apt-get update
          sudo apt-get install -y openjdk-8-jdk
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: |
          echo "Install leiningen"
          mkdir -p $HOME/local/bin
          wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
          mv lein $HOME/local/bin/lein
          chmod a+x $HOME/local/bin/lein
      - run: |
          echo "run tests"
          export PATH=$PATH:$HOME/local/bin
          sudo lein version
          lein test
